# Generated by Django 5.2.4 on 2025-08-13 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre_of_book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='genre_of_book', to='books.genre'),
        ),
    ]
